RabbitMQ:
  image: "rabbitmq:3"
  environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
  ports:
    - "5672:5672"

Redis:
  image: 'redis:alpine'
  ports:
    - "6379:6379"

ElasticSearch:
  image: 'elasticsearch:5-alpine'
  ports:
    - "9200:9200"
  volumes:
    - ./volumes/esdata:/usr/share/elasticsearch/data
