RabbitMQ:
  image: "rabbitmq:3"
  environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
  ports:
    - "5672:5672"

Redis:
  image: 'redis:alpine'
  ports:
    - "6379:6379"
