campaigns_runner_service: nameko run --config nameko.yml app:CampaignsRunnerService
campaign_service: nameko run --config nameko.yml app:CampaignService
stats_service: nameko run --config nameko.yml app:StatsService
subscriber_service: nameko run --config nameko.yml app:SubscriberService
campaign_processor_service: nameko run --config nameko.yml app:CampaignProcessorService
queue: nameko run --config nameko.yml app:Queue
counter_service: nameko run --config nameko.yml app:CounterService
subscriber_processor_service: nameko run --config nameko.yml app:SubscriberProcessorService
subscriber_remote_storage_service: nameko run --config nameko.yml app:SubscriberRemoteStorageService
syncer_service: nameko run --config nameko.yml app:SyncerService
syncer_page_processor_service: nameko run --config nameko.yml app:SyncerPageProcessorService
syncer_subscriber_persister_service: nameko run --config nameko.yml app:SyncerSubscriberPersisterService
